name: SpringBoot CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Jave
      uses: actions/steup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Application
      uses: mvn clean package

    -name:
      run:
    permissions:
      contents: read
      packages: write
      - name: login to GHCR
        uses: docker/login-action@v3